services:
  postgres:
    image: postgres:15
    container_name: communitas-postgresql
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - communitas-data:/var/lib/postgresql/data

volumes:
  communitas-data:
